const ErrorCode = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNAUTHOURIZED: 'UNAUTHOURIZED',
  NOT_FOUND: 'NOT_FOUND',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_CSRF_TOKEN: 'INVALID_CSRF_TOKEN',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP EXPIRED',
  MFA_ENABLED_ERROR: 'MFA_ENABLED_ERROR',
  INVALID_CAPTCHA: 'INVALID_CAPTCHA'
};

export default ErrorCode;
