const AuthType = {
  MFA_AUTH: 'MFA_AUTH',
  CUSTOM_AUTH: 'CUSTOM_AUTH',
  VERIFY_MOBILE_OTP: 'VERIFY_MOBILE_OTP',
  USER_PASSWORD_AUTH: 'USER_PASSWORD_AUTH',
  AUTHORIZATION_CODE: 'AUTHORIZATION_CODE'
};

const ProviderType = {
  USER_PASSWORD_AUTH: 'USER_PASSWORD_AUTH',
  GOOGLE_AUTH: 'GOOGLE_AUTH'
};

const MfaType = {
  SMS_MFA: 'SMS_MFA',
  SOFTWARE_TOKEN_MFA: 'SOFTWARE_TOKEN_MFA',
  CUSTOM_CHALLENGE: 'CUSTOM_CHALLENGE'
};

export { AuthType, MfaType, ProviderType };
